image:
	docker build -t minforth .
run:
	docker run --rm -i -t -v $(HOME)/Projects/docker-forth/src:/src minforth

xlerb:
	docker run --rm -i -t -v $(HOME)/Projects/docker-forth/src:/src minforth include xlerb.fs bye
