name: Build and push cforth Docker-Forth image

on:
  push:
    branches: [ master ]
    paths:
       - 'cforth/**'
  pull_request:
    branches: [ master ]
    paths:
       - 'cforth/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push cforth
        uses: docker/build-push-action@v2
        with:
          context: ./cforth
          push: true
          tags: rundockerforth/cforth:latest
