name: Build and push gforth32-0.6.2-7.3_libffcall1 Docker-Forth image

on:
  push:
    branches: [ master ]
    paths:
       - 'gforth32-0.6.2-7.3_libffcall1/**'
  pull_request:
    branches: [ master ]
    paths:
       - 'gforth32-0.6.2-7.3_libffcall1/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gforth32-0.6.2-7.3_libffcall1
        uses: docker/build-push-action@v2
        with:
          context: ./gforth32-0.6.2-7.3_libffcall1
          push: true
          tags: rundockerforth/gforth32-0.6.2-7.3_libffcall1:latest
