name: Build and push kforth64 Docker-Forth image

on:
  push:
    branches: [ master ]
    paths:
       - 'kforth64/**'
  pull_request:
    branches: [ master ]
    paths:
       - 'kforth64/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push kforth64
        uses: docker/build-push-action@v2
        with:
          context: ./kforth64
          push: true
          tags: rundockerforth/kforth64:latest
