name: Build and push minforth3.4 Docker-Forth image

on:
  push:
    branches: [ master ]
    paths:
       - 'minforth3.4/**'
  pull_request:
    branches: [ master ]
    paths:
       - 'minforth3.4/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push minforth3.4
        uses: docker/build-push-action@v2
        with:
          context: ./minforth3.4
          push: true
          tags: rundockerforth/minforth3.4:latest
